### ISSUE TITLE
Compiling PEAT from source - minimum version of BOOST?

### ISSUE THREAD

**Issue by tseemann** [jhhung/PEAT#12]
I tried to compile on Ubuntu 12 with CC=gcc-4.7 and CXX=g++-4.7 and Boost 1.46.1 and got this error:

```
/usr/include/boost/thread/future.hpp: In instantiation of ‘boost::unique_future<R>::unique_future(boost::unique_future<R>::future_ptr) [with R = void; boost::unique_future<R>::future_ptr = boost::shared_ptr<boost::detail::future_object<void> >]’:
/usr/include/boost/thread/future.hpp:1134:46:   required from here
/usr/include/boost/thread/future.hpp:634:27: error: use of deleted function ‘boost::shared_ptr<boost::detail::future_object<void> >::shared_ptr(const boost::shared_ptr<boost::detail::future_object<void> >&)’
‘
Internal compiler error: Error reporting routines re-entered.
```

Is there a minimum Boost version?

```
-- Boost version: 1.46.1
-- Boost version: 1.46.1
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   system
--   serialization
--   system
--   filesystem
--   regex
--   thread
--   iostreams
--   program_options
-- Configuring done
```

**Comment by jhhung** [comment]
Yes, please use the newest version of Boost and compile it with GCC 4.8.

**Comment by tseemann** [comment]
I am not able to compile with GCC 4.8, our system does not have it installed.

What version of BOOST does it actually need?

**Comment by jhhung** [comment]
We used 1.53 for development.

**Comment by tseemann** [comment]
Ok thank you.
